name: Feature Request
description: Suggest a new idea for the project
title: "[Feature]: "
labels: ["feature"]
assignees: []
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to suggest?
    validations:
      required: true
  - type: input
    id: epic
    attributes:
      label: Epic
      description: If this feature is part of an epic, please specify it.
