on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 16 * * 4'
    - cron: '0 17 * * 4'

jobs:
  move-to-next-iteration:
    name: Move to next iteration
    runs-on: ubuntu-latest

    steps:
      - uses: blombard/move-to-next-iteration@master
        with:
          owner: codecov
          number: 31 # Applications
          token: ${{ secrets.PAT_TOKEN }}
          iteration-field: Sprint
          iteration: last
          new-iteration: current
          statuses: Todo,In Progress,In Review,Merged
